echo -ne ">\r";
  sleep 0.3;
  echo -ne "=-\r";
  sleep 0.3;
  echo -ne "-=>\r";
  sleep 0.3;
  echo -ne ".-=-\r";
  sleep 0.3;
  echo -ne "..-=>\r";
  sleep 0.3;
  echo -ne "...-=-\r";
  sleep 0.3;
  echo -ne "....-=>\r";
  sleep 0.3;
  echo -ne ".....-=-\r";
  sleep 0.3;
  echo -ne "......-=>\r";
  sleep 0.3;
  echo -ne ".......-=-\r";
  sleep 0.3;
  echo -ne "........-=>\r";
  sleep 0.3;
  echo -ne ".........-=-\r";
  sleep 0.3;
  echo -ne "..........-=>\r";
  sleep 0.3;
  echo -ne "...........-=-\r";
  sleep 0.3;
  echo -ne "............-=>\r";
  sleep 0.3;
  echo -ne ".............-=-\r";
  sleep 0.3;
  echo -ne "..............-=>\r";
  sleep 0.3;
  echo -ne "...............-=-\r";
  sleep 0.3;
  echo -ne "................-=>\r";
  sleep 0.3;
  echo -ne ".................-=-\r";
  sleep 0.3;
  echo -ne "..................-=>\r";
  sleep 0.3;
  echo -ne "...................-=-\r";
  sleep 0.3;
  echo -ne "....................-=>\r";
  sleep 0.3;
  echo -ne ".....................-=-\r";
  sleep 0.3;
  echo -ne "......................-=>\r";
  sleep 0.3;
  echo -ne ".......................-=-\r";
  sleep 0.3;
  echo -ne "........................-=>\r";
  sleep 0.3;
  echo -ne ".........................-=-\r";
  sleep 0.3;
  echo -ne "..........................-=>\r";
  sleep 0.3;
  echo -ne "...........................-=-\r";
  sleep 0.3;
    echo -ne "..........................-=>\r";
  sleep 0.3;
